# Basic Python

## 1. Split this string

In [7]:
name = "Hello, this is Rohit"

In [32]:
name.split()

['Hello,', 'this', 'is', 'Rohit']

## 2. Use .format() to print the following string.

### Output should be: The diameter of Earth is 12742 kilometers.

In [31]:
diameter = 12742
"The diameter of Earth is {} kilometers".format(diameter)

'The diameter of Earth is 12742 kilometers'

## 3. In this nested dictionary, grab the word "hello"

In [10]:
nest = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [30]:
nest['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [2]:
import numpy as np

## 4.1 Create an array of 10 zeros?

## 4.2 Create an array of 10 fives?

In [3]:
arr = np.zeros(10, dtype = 'int64')
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [4]:
arr = np.ones(10, dtype = 'int64')*5
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

## 5. Create an array of all the even integers from 20 to 35

In [5]:
arr = np.arange(20,35,2)
arr

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [7]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
np.concatenate((n1,n2), axis = 0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [8]:
import pandas as pd

In [9]:
chess = ['knight', 'bishop', 'king']
dataframe = pd.DataFrame(chess, columns = ["data"])
dataframe

data
0  knight
1  bishop
2    king

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [10]:
list_of_dates = pd.date_range(start='1-01-2023', end = '2-10-2023')
list_of_dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

In [11]:
list_of_data = [[1, "aaa", 22], [2, "bbb", 25], [3, "ccc", 24]]
data = pd.DataFrame(list_of_data, columns = ["digits", "letters", "numbers"])
data

digits letters  numbers
0       1     aaa       22
1       2     bbb       25
2       3     ccc       24